services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-DESKTOP-IE8NCSC}"
    image: cybulde-data-processing
    platform: linux/amd64
    container_name: cybulde-data-processing-container
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/emkademy-474323-887fb2819a7a.json
      #- GOOGLE_APPLICATION_CREDENTIALS= app/creds/emkademy-474323-887fb2819a7a.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-caner}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-caner}/.config/gcloud
    ports:
      - "8888:8888"
      - "8080:8080"
    ipc: host
    init: true
